### ISSUE TITLE
bad suggestions when typing single digit numbers with measurements

### ISSUE THREAD

**Issue by s-i-m-s** [bartekplus/FluentTyper#19]
For example if I try to type 5mm and hit enter the 5 is removed so I it just says mm.

It gives mm as the first suggestion so that's what you expect to happen on pressing enter but that doesn't appear to be a desirable or correct auto correction.

It also does this with other measurements like ft, in, lbs and so on.

For how short measurement abbreviations typically are it probably shouldn't even be trying to handle them.

**Comment by bartekplus** [comment]
Hey @s-i-m-s  
The general rule is to put a space between a number and a unit of measurement. So the "5mm" is not correct. 
FluentTyper doesn't generate predictions for numbers.  The exception is if only a single digit is in your word, then it will treat it as a typo and suggest the most probable word.  That's why you see "mm" for "5mm" input. 

Please note that FF is not made to fix all grammar issue,  you have LanguageTool or Grammarly for that. 
I'm not sure if I would like to start implementing all grammar rules in FF.

**Comment by s-i-m-s** [comment]
In normal typing like in a comment it's not an issue.
For search queries or form filling it can be annoying. Of course it's only an issue if its at the end of the query
Like I can type "keltec 9mm" and since I hit enter at the end of the query it changes to "keltec mm" If I swap the order to "9mm keltec" it changes it to "9mm kilter"

I'm going to call this user error as I can't think of a way to fix it without breaking the functionality and just add the sites giving me this issue to the blacklist...ok so the blacklist function doesn't seem to work, i'll open another issue for that.

**Comment by bartekplus** [comment]
"Won't fix"
